### ISSUE TITLE
JAR

### ISSUE THREAD

**Issue by ingconti** [rohit20v/tcp_chatroom#3]
I succeded in building

ava -jar tcp_chatroom.jar

but OI got:
Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ExecutorService.shutdown()" because "this.pool" is null
	at org.chatroom.Server.Server.shutdown(Server.java:72)
	at org.chatroom.Server.Server.run(Server.java:39)
	at java.base/java.lang.Thread.run(Thread.java:1570)

FIX ASAP!

**Comment by ingconti** [comment]
where is JAR? make a folder "deliverables" or "JARs" and copy there final JAR/s
